### ISSUE TITLE
Merge task depencences and task creation event

### ISSUE THREAD

**Issue by jprotze** [OpenMPToolsInterface/OMPT-Technical-Report#3]
Currently the spec contains these callbacks for task creation:

```
/* ompt_event_task_create */
typedef void (*ompt_task_create_callback_t) (
  ompt_task_id_t parent_task_id,
  const ompt_frame_t *parent_frame,
  ompt_task_id_t new_task_id,
  ompt_task_type_t type,
  const void *codeptr_ra
);

/* ompt_event_task_dependences */
typedef void (*ompt_task_dependences_callback_t) (
  ompt_task_id_t task_id,
  const ompt_task_dependence_t *deps,
  int ndeps
);
```

Specification of the latter says:

> The OpenMP runtime invokes this callback after an explicit task is created, but before the task begins execution to announce its dependences with respect to data objects.

For deadlock detection, I need the depencency information right on the creation of the task (OpenMP spec uses the wording "generating a task")

Proposal as discussed in concall 5/11/16:

```
/* ompt_event_task_create */
typedef void (*ompt_task_create_callback_t) (
  ompt_task_id_t parent_task_id,
  const ompt_frame_t *parent_frame,
  ompt_task_id_t new_task_id,
  ompt_task_type_t type,
  const void *codeptr_ra
);

/* ompt_event_task_create_with_depencences */
typedef void (*ompt_task_create_with_dependences_callback_t) (
  ompt_task_id_t parent_task_id,
  const ompt_frame_t *parent_frame,
  ompt_task_id_t new_task_id,
  ompt_task_type_t type,
  const ompt_task_dependence_t *deps,
  int ndeps,
  const void *codeptr_ra
);
```

The idea is, that a tool can decide, which event to register (potentially higher overhead for the latter). Both events would trigger at the same places. For tasks without depencences: deps=NULL, ndeps=0.
Similar to the old dependences event, the second version could be optional.

**Comment by jmellorcrummey** [comment]
From my perspective, having the two orthogonal calls has some appeal rather than duplicating the task create concept into the merged call. For that reason, I'd like to hear a bit more justification for your proposal.

Why do you need the dependence info directly at creation? I can't imagine why saving the info at creation to process when the second callback occurs wouldn't suffice. We could guarantee that the second callback would occur even if 0 dependences are present.

## 

John Mellor-Crummey

(sent from my phone)

**Comment by jprotze** [comment]
With the current specification, the dependences event can be triggered just before the task gets scheduled. That is, when all dependences are solved anyway. 
This is too late, to base deadlock analysis on this event. The analysis would assume, that there is a task in the queue that can be scheduled, but the task is blocked due to dependences. 

So, my initial proposal was to specify, that the dependences event needs to trigger right with the task creation event. Folks in the concall then suggested to merge the events and have the two versions.

**Comment by jmellorcrummey** [comment]
Joachim,

I like your original proposal: having the dependences callback trigger early. Having the calls separate was part of a broader goal of avoiding composite calls, which we applied to target callbacks in particular.

However, If the consensus is for adding the combined call, I would reluctantly go along.

## 

John Mellor-Crummey

(sent from my phone)

**Comment by AlexandreEichenberger** [comment]
Joaquim,
 
task dependences must be build prior to doing anything with a task. So 1) we create a task, 2) we build dependences, 3) we determine if the task is ready and we want to execute it now, or not ready or we want to delay it.
 
It makes no sense to give you dependences before giving you the callback for the new task. 
 
We can add "callback for depenences occurs just after calllback for task creation"
 
I don't think it will hinder any runtime, because legally, we cannot delay discovering dependences. The only case I could imagine where we would not build dependences is if the parallel region in which it execute is sequential, or we are in "final" mode...
 
So in fact, you may not get the dep info if it runs sequentially.... (by def of OpenMP, we have no way to discover dependences of a sequential execution... check the model, happy totalk if you disagree)
Alexandre-----------------------------------------------------------------------------------------------------Alexandre Eichenberger, Master Inventor, Advanced Compiler Technologies- research: compiler optimization (OpenMP, multithreading, SIMD)- info: alexe@us.ibm.com http://www.research.ibm.com/people/a/alexe- phone: 914-945-1812 (work) 914-312-3618 (cell)
 
 
----- Original message -----From: John Mellor-Crummey notifications@github.comTo: OpenMPToolsInterface/OMPT-Technical-Report OMPT-Technical-Report@noreply.github.comCc:Subject: Re: [OpenMPToolsInterface/OMPT-Technical-Report] Merge task depencences and task creation event (#3)Date: Wed, Jun 1, 2016 8:33 AM Joachim,I like your original proposal: having the dependences callback trigger early. Having the calls separate was part of a broader goal of avoiding composite calls, which we applied to target callbacks in particular.However, If the consensus is for adding the combined call, I would reluctantly go along.--John Mellor-Crummey(sent from my phone)> On Jun 1, 2016, at 7:19 AM, Joachim notifications@github.com wrote:>> With the current specification, the dependences event can be triggered just before the task gets scheduled. That is, when all dependences are solved anyway.> This is too late, to base deadlock analysis on this event. The analysis would assume, that there is a task in the queue that can be scheduled, but the task is blocked due to dependences.>> So, my initial proposal was to specify, that the dependences event needs to trigger right with the task creation event. Folks in the concall then suggested to merge the events and have the two versions.>> —> You are receiving this because you commented.> Reply to this email directly, view it on GitHub, or mute the thread.>> !DSPAM:8504,574ed2fa267749343481409!

**Comment by jprotze** [comment]
> task dependences must be build prior to doing anything with a task. So 1) we create a task, 2) we build dependences, 3) we determine if the task is ready and we want to execute it now, or not ready or we want to delay it.
> 
> It makes no sense to give you dependences before giving you the callback for the new task. 

I didn't ask for "before". I asked for "with" or "right after" the callback for the newly generated task.
As I understand the callback definition for the task dependency event, this is the raw data, put on the pragma line:

`#pragma omp task depend (in: a,b)`
results in 
`ompt_event_task_dependences(taskid, {{&a,IN},{&b,IN}}, 2);`

I don't think, that you need to build/evaluate the dependencies, to trigger the task-creation and the task-dependency event?

**Comment by jmellorcrummey** [comment]
The task dependence info for OMPT will have to be built, unless we can get every compiler/runtime to agree on a common representation of this info at runtime (unlikely). However, the dependences don't need to be checked before reporting them with OMPT.

## 

John Mellor-Crummey

(sent from my phone)

**Comment by AlexandreEichenberger** [comment]
Joachim,
 
is it enough for you if we say "just after?" Since its not a mandatory callback, if you don't support this, you still have to have the combined callback but with no dep info... its complicate the interface, so I also prefer to keep it separate
Alexandre-----------------------------------------------------------------------------------------------------Alexandre Eichenberger, Master Inventor, Advanced Compiler Technologies- research: compiler optimization (OpenMP, multithreading, SIMD)- info: alexe@us.ibm.com http://www.research.ibm.com/people/a/alexe- phone: 914-945-1812 (work) 914-312-3618 (cell)
 
 
----- Original message -----From: John Mellor-Crummey notifications@github.comTo: OpenMPToolsInterface/OMPT-Technical-Report OMPT-Technical-Report@noreply.github.comCc: Alexandre Eichenberger/Watson/IBM@IBMUS, Comment comment@noreply.github.comSubject: Re: [OpenMPToolsInterface/OMPT-Technical-Report] Merge task depencences and task creation event (#3)Date: Wed, Jun 1, 2016 9:42 AM The task dependence info for OMPT will have to be built, unless we can get every compiler/runtime to agree on a common representation of this info at runtime (unlikely). However, the dependences don't need to be checked before reporting them with OMPT.--John Mellor-Crummey(sent from my phone)> On Jun 1, 2016, at 8:17 AM, Joachim notifications@github.com wrote:>> task dependences must be build prior to doing anything with a task. So 1) we create a task, 2) we build dependences, 3) we determine if the task is ready and we want to execute it now, or not ready or we want to delay it.>> It makes no sense to give you dependences before giving you the callback for the new task.>> I didn't ask for "before". I asked for "with" or "right after" the callback for the newly generated task.> As I understand the callback definition for the task dependency event, this is the raw data, put on the pragma line:>> #pragma omp task depend (in: a,b)> results in> ompt_event_task_dependences(taskid, {{&a,IN},{&b,IN}}, 2);>> I don't think, that you need to build/evaluate the dependencies, to trigger the task-creation and the task-dependency event?>> —> You are receiving this because you commented.> Reply to this email directly, view it on GitHub, or mute the thread.>> !DSPAM:8504,574ee082267742763516592!

**Comment by jprotze** [comment]
> Since its not a mandatory callback, if you don't support this, you still have to have the combined callback but with no dep info... 

In my initial posting, my last point was, that `ompt_event_task_create_with_depencences` should be optional like `ompt_event_task_dependences` is now. So a runtime is free to mark this callback as "not implemented". In that case, the runtime does not need to trigger the combined callback.

From the tools perspective, I'd like to know, whether I need to expect a dependency information callback after the task creation callback. So, if we keep the calls separated, I'd like to add a `has_depencency` flag to the task-creation callback.

**Comment by jmellorcrummey** [comment]
I vote for the has_dependency argument. That is simple and useful, as you describe. It's better than a mandatory dependence callback that reports no dependences.

## 

John Mellor-Crummey

(sent from my phone)

**Comment by jprotze** [comment]
The combined version is **not** mandatory. 
Only the old version of the callback is mandatory.

**Comment by jmellorcrummey** [comment]
The argument has_dependences has been added to ompt_event_task_create.
The description of the event ompt_event_task_dependences has been modified to indicate that the runtime invokes this callback immediately after the callback announcing task creation.
